AllCops:
  TargetRubyVersion: 1.9
  Exclude:
    - 'modules/**/*'
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/TrailingCommaInLiteral:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/NumericLiterals:
  Enabled: false

# This check errors out on Ruby 1.9.3 on Travis for some reason :-/
Style/WordArray:
  Enabled: false

# Increase linelength to match Puppet style guide
Metrics/LineLength:
  Max: 140
